package ni.edu.mney.domain;

import static ni.edu.mney.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AuditoriaAccionesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditoriaAccionesAllPropertiesEquals(AuditoriaAcciones expected, AuditoriaAcciones actual) {
        assertAuditoriaAccionesAutoGeneratedPropertiesEquals(expected, actual);
        assertAuditoriaAccionesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditoriaAccionesAllUpdatablePropertiesEquals(AuditoriaAcciones expected, AuditoriaAcciones actual) {
        assertAuditoriaAccionesUpdatableFieldsEquals(expected, actual);
        assertAuditoriaAccionesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditoriaAccionesAutoGeneratedPropertiesEquals(AuditoriaAcciones expected, AuditoriaAcciones actual) {
        assertThat(actual)
            .as("Verify AuditoriaAcciones auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditoriaAccionesUpdatableFieldsEquals(AuditoriaAcciones expected, AuditoriaAcciones actual) {
        assertThat(actual)
            .as("Verify AuditoriaAcciones relevant properties")
            .satisfies(a -> assertThat(a.getEntidad()).as("check entidad").isEqualTo(expected.getEntidad()))
            .satisfies(a -> assertThat(a.getAccion()).as("check accion").isEqualTo(expected.getAccion()))
            .satisfies(a ->
                assertThat(a.getFecha()).as("check fecha").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getFecha())
            )
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditoriaAccionesUpdatableRelationshipsEquals(AuditoriaAcciones expected, AuditoriaAcciones actual) {
        // empty method
    }
}
