package ni.edu.mney.domain;

import static ni.edu.mney.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CitaMedicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitaMedicaAllPropertiesEquals(CitaMedica expected, CitaMedica actual) {
        assertCitaMedicaAutoGeneratedPropertiesEquals(expected, actual);
        assertCitaMedicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitaMedicaAllUpdatablePropertiesEquals(CitaMedica expected, CitaMedica actual) {
        assertCitaMedicaUpdatableFieldsEquals(expected, actual);
        assertCitaMedicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitaMedicaAutoGeneratedPropertiesEquals(CitaMedica expected, CitaMedica actual) {
        assertThat(actual)
            .as("Verify CitaMedica auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitaMedicaUpdatableFieldsEquals(CitaMedica expected, CitaMedica actual) {
        assertThat(actual)
            .as("Verify CitaMedica relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaHora())
                    .as("check fechaHora")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaHora())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitaMedicaUpdatableRelationshipsEquals(CitaMedica expected, CitaMedica actual) {
        assertThat(actual)
            .as("Verify CitaMedica relationships")
            .satisfies(a -> assertThat(a.getPaciente()).as("check paciente").isEqualTo(expected.getPaciente()));
    }
}
