package ni.edu.mney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsultaMedicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaMedicaAllPropertiesEquals(ConsultaMedica expected, ConsultaMedica actual) {
        assertConsultaMedicaAutoGeneratedPropertiesEquals(expected, actual);
        assertConsultaMedicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaMedicaAllUpdatablePropertiesEquals(ConsultaMedica expected, ConsultaMedica actual) {
        assertConsultaMedicaUpdatableFieldsEquals(expected, actual);
        assertConsultaMedicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaMedicaAutoGeneratedPropertiesEquals(ConsultaMedica expected, ConsultaMedica actual) {
        assertThat(actual)
            .as("Verify ConsultaMedica auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaMedicaUpdatableFieldsEquals(ConsultaMedica expected, ConsultaMedica actual) {
        assertThat(actual)
            .as("Verify ConsultaMedica relevant properties")
            .satisfies(a -> assertThat(a.getFechaConsulta()).as("check fechaConsulta").isEqualTo(expected.getFechaConsulta()))
            .satisfies(a -> assertThat(a.getMotivoConsulta()).as("check motivoConsulta").isEqualTo(expected.getMotivoConsulta()))
            .satisfies(a -> assertThat(a.getNotasMedicas()).as("check notasMedicas").isEqualTo(expected.getNotasMedicas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaMedicaUpdatableRelationshipsEquals(ConsultaMedica expected, ConsultaMedica actual) {
        assertThat(actual)
            .as("Verify ConsultaMedica relationships")
            .satisfies(a -> assertThat(a.getExpediente()).as("check expediente").isEqualTo(expected.getExpediente()));
    }
}
