package ni.edu.mney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiagnosticoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoAllPropertiesEquals(Diagnostico expected, Diagnostico actual) {
        assertDiagnosticoAutoGeneratedPropertiesEquals(expected, actual);
        assertDiagnosticoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoAllUpdatablePropertiesEquals(Diagnostico expected, Diagnostico actual) {
        assertDiagnosticoUpdatableFieldsEquals(expected, actual);
        assertDiagnosticoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoAutoGeneratedPropertiesEquals(Diagnostico expected, Diagnostico actual) {
        assertThat(actual)
            .as("Verify Diagnostico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoUpdatableFieldsEquals(Diagnostico expected, Diagnostico actual) {
        assertThat(actual)
            .as("Verify Diagnostico relevant properties")
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCodigoCIE()).as("check codigoCIE").isEqualTo(expected.getCodigoCIE()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoUpdatableRelationshipsEquals(Diagnostico expected, Diagnostico actual) {
        assertThat(actual)
            .as("Verify Diagnostico relationships")
            .satisfies(a -> assertThat(a.getConsulta()).as("check consulta").isEqualTo(expected.getConsulta()));
    }
}
