package ni.edu.mney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExpedienteClinicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpedienteClinicoAllPropertiesEquals(ExpedienteClinico expected, ExpedienteClinico actual) {
        assertExpedienteClinicoAutoGeneratedPropertiesEquals(expected, actual);
        assertExpedienteClinicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpedienteClinicoAllUpdatablePropertiesEquals(ExpedienteClinico expected, ExpedienteClinico actual) {
        assertExpedienteClinicoUpdatableFieldsEquals(expected, actual);
        assertExpedienteClinicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpedienteClinicoAutoGeneratedPropertiesEquals(ExpedienteClinico expected, ExpedienteClinico actual) {
        assertThat(actual)
            .as("Verify ExpedienteClinico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpedienteClinicoUpdatableFieldsEquals(ExpedienteClinico expected, ExpedienteClinico actual) {
        assertThat(actual)
            .as("Verify ExpedienteClinico relevant properties")
            .satisfies(a -> assertThat(a.getNumeroExpediente()).as("check numeroExpediente").isEqualTo(expected.getNumeroExpediente()))
            .satisfies(a -> assertThat(a.getFechaApertura()).as("check fechaApertura").isEqualTo(expected.getFechaApertura()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpedienteClinicoUpdatableRelationshipsEquals(ExpedienteClinico expected, ExpedienteClinico actual) {
        // empty method
    }
}
