package ni.edu.mney.domain;

import static ni.edu.mney.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class HistorialClinicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialClinicoAllPropertiesEquals(HistorialClinico expected, HistorialClinico actual) {
        assertHistorialClinicoAutoGeneratedPropertiesEquals(expected, actual);
        assertHistorialClinicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialClinicoAllUpdatablePropertiesEquals(HistorialClinico expected, HistorialClinico actual) {
        assertHistorialClinicoUpdatableFieldsEquals(expected, actual);
        assertHistorialClinicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialClinicoAutoGeneratedPropertiesEquals(HistorialClinico expected, HistorialClinico actual) {
        assertThat(actual)
            .as("Verify HistorialClinico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialClinicoUpdatableFieldsEquals(HistorialClinico expected, HistorialClinico actual) {
        assertThat(actual)
            .as("Verify HistorialClinico relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaRegistro())
                    .as("check fechaRegistro")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaRegistro())
            )
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorialClinicoUpdatableRelationshipsEquals(HistorialClinico expected, HistorialClinico actual) {
        assertThat(actual)
            .as("Verify HistorialClinico relationships")
            .satisfies(a -> assertThat(a.getExpediente()).as("check expediente").isEqualTo(expected.getExpediente()));
    }
}
