package ni.edu.mney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetaAllPropertiesEquals(Receta expected, Receta actual) {
        assertRecetaAutoGeneratedPropertiesEquals(expected, actual);
        assertRecetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetaAllUpdatablePropertiesEquals(Receta expected, Receta actual) {
        assertRecetaUpdatableFieldsEquals(expected, actual);
        assertRecetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetaAutoGeneratedPropertiesEquals(Receta expected, Receta actual) {
        assertThat(actual)
            .as("Verify Receta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetaUpdatableFieldsEquals(Receta expected, Receta actual) {
        assertThat(actual)
            .as("Verify Receta relevant properties")
            .satisfies(a -> assertThat(a.getDosis()).as("check dosis").isEqualTo(expected.getDosis()))
            .satisfies(a -> assertThat(a.getFrecuencia()).as("check frecuencia").isEqualTo(expected.getFrecuencia()))
            .satisfies(a -> assertThat(a.getDuracion()).as("check duracion").isEqualTo(expected.getDuracion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetaUpdatableRelationshipsEquals(Receta expected, Receta actual) {
        assertThat(actual)
            .as("Verify Receta relationships")
            .satisfies(a -> assertThat(a.getMedicamento()).as("check medicamento").isEqualTo(expected.getMedicamento()))
            .satisfies(a -> assertThat(a.getConsulta()).as("check consulta").isEqualTo(expected.getConsulta()));
    }
}
