package ni.edu.mney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SignosVitalesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAllPropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertSignosVitalesAutoGeneratedPropertiesEquals(expected, actual);
        assertSignosVitalesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAllUpdatablePropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertSignosVitalesUpdatableFieldsEquals(expected, actual);
        assertSignosVitalesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAutoGeneratedPropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(actual)
            .as("Verify SignosVitales auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesUpdatableFieldsEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(actual)
            .as("Verify SignosVitales relevant properties")
            .satisfies(a -> assertThat(a.getPeso()).as("check peso").isEqualTo(expected.getPeso()))
            .satisfies(a -> assertThat(a.getAltura()).as("check altura").isEqualTo(expected.getAltura()))
            .satisfies(a -> assertThat(a.getPresionArterial()).as("check presionArterial").isEqualTo(expected.getPresionArterial()))
            .satisfies(a -> assertThat(a.getTemperatura()).as("check temperatura").isEqualTo(expected.getTemperatura()))
            .satisfies(a -> assertThat(a.getFrecuenciaCardiaca()).as("check frecuenciaCardiaca").isEqualTo(expected.getFrecuenciaCardiaca())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesUpdatableRelationshipsEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(actual)
            .as("Verify SignosVitales relationships")
            .satisfies(a -> assertThat(a.getConsulta()).as("check consulta").isEqualTo(expected.getConsulta()));
    }
}
