package ni.edu.mney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TratamientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAllPropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertTratamientoAutoGeneratedPropertiesEquals(expected, actual);
        assertTratamientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAllUpdatablePropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertTratamientoUpdatableFieldsEquals(expected, actual);
        assertTratamientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAutoGeneratedPropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(actual)
            .as("Verify Tratamiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoUpdatableFieldsEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(actual)
            .as("Verify Tratamiento relevant properties")
            .satisfies(a -> assertThat(a.getIndicaciones()).as("check indicaciones").isEqualTo(expected.getIndicaciones()))
            .satisfies(a -> assertThat(a.getDuracionDias()).as("check duracionDias").isEqualTo(expected.getDuracionDias()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoUpdatableRelationshipsEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(actual)
            .as("Verify Tratamiento relationships")
            .satisfies(a -> assertThat(a.getConsulta()).as("check consulta").isEqualTo(expected.getConsulta()));
    }
}
